quarkus.http.port=8080
quarkus.http.host=0.0.0.0

quarkus.log.level=INFO
quarkus.log.category."com.redhat.openshift".level=DEBUG

quarkus.kubernetes-client.trust-certs=true

quarkus.smallrye-health.root-path=/q/health
